// <auto-generated />
using System;
using AzureDeveloperTemplates.Starter.Infrastructure.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AzureDeveloperTemplates.Starter.Infrastructure.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20200415182240_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureDeveloperTemplates.Starter.Core.DomainModel.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99375b4c-f052-428a-be5c-ab7d62f556dc"),
                            Name = "Samsung TV"
                        },
                        new
                        {
                            Id = new Guid("06d99ab2-f016-4c52-824e-88cc9bb8fa6a"),
                            Name = "MacBook"
                        },
                        new
                        {
                            Id = new Guid("dd9cfa67-c498-4397-b3dc-63646e7086ef"),
                            Name = "Surface Laptop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
